# Generated by Django 4.0.1 on 2022-01-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticSystem', '0002_answers_cabinet_diagnostic_diagnosticlist_disease_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.questions', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='diagnosticlist',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='diagnosticlist',
            name='diagnostic_date',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Дата диагностирования'),
        ),
        migrations.AlterField(
            model_name='diagnosticlist',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='diagnosticlist',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='diseasediagnostics',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='diseasediagnostics',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.speciality', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patronymic',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patientanswers',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.answers', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='patientanswers',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='patientanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.questions', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='price',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика'),
        ),
        migrations.AlterField(
            model_name='price',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.employee', verbose_name='Сотрудник'),
        ),
    ]
