# Generated by Django 4.0.1 on 2022-06-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Ответ')),
                ('number_of_points', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество баллов')),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер кабинета')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Диагностика')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Заболевание')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.cabinet', verbose_name='Кабинет')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipChart',
            fields=[
                ('membership_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='График принадлежности №')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название специальности')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.employee', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnswers',
            fields=[
                ('answer_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Дата ответа')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.answers', verbose_name='Ответ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.patient', verbose_name='Пациент')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.questions', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=50, verbose_name='Название функции')),
                ('a', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('c', models.PositiveSmallIntegerField()),
                ('d', models.PositiveSmallIntegerField()),
                ('membership_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.membershipchart', verbose_name='График принадлежности')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.speciality', verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='DiseaseDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.disease', verbose_name='Заболевание')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='membership_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.membershipchart', verbose_name='График принадлежности'),
        ),
        migrations.CreateModel(
            name='DiagnosticList',
            fields=[
                ('result', models.TextField(verbose_name='Список диагностик пациента')),
                ('diagnostic_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Дата диагностирования')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.diagnostic', verbose_name='Диагностика')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.employee', verbose_name='Сотрудник')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.patient', verbose_name='Пациент')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.disease', verbose_name='Заболевание'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.questions', verbose_name='Вопрос'),
        ),
    ]
