# Generated by Django 4.0.1 on 2022-07-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticSystem', '0002_remove_patient_name_remove_patient_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipfunction',
            name='membership_chart',
            field=models.ForeignKey(choices=[('LC', 'Низкая вероятность'), ('AC', 'Средняя вероятность'), ('HC', 'Высокая вероятность')], on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.membershipchart', verbose_name='График принадлежности'),
        ),
    ]
