# Generated by Django 4.0.1 on 2022-07-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnosticSystem', '0003_alter_membershipfunction_membership_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanswers',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipfunction',
            name='function_name',
            field=models.CharField(choices=[('LC', 'Низкая вероятность'), ('AC', 'Средняя вероятность'), ('HC', 'Высокая вероятность')], max_length=50, verbose_name='Название функции'),
        ),
        migrations.AlterField(
            model_name='membershipfunction',
            name='membership_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DiagnosticSystem.membershipchart', verbose_name='График принадлежности'),
        ),
        migrations.AlterField(
            model_name='patientanswers',
            name='answer_date',
            field=models.DateTimeField(verbose_name='Дата ответа'),
        ),
    ]
